/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    locations: Location;
    activities: Activity;
    bookings: Booking;
    'blog-posts': BlogPost;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'de') | ('en' | 'fr' | 'de')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'terms-page': TermsPage;
    'privacy-page': PrivacyPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'terms-page': TermsPageSelect<false> | TermsPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
  };
  locale: 'en' | 'fr' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  /**
   * Optional: Paste an external URL (e.g. from UploadThing) instead of uploading a file
   */
  externalUrl?: string | null;
  _key?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage activity and transport categories
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Category name (e.g., "Desert Adventures", "Mountain Adventures")
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  type: 'activity' | 'transport';
  /**
   * Duration type shown on category cards
   */
  durationType?: ('multi-day' | 'day-trip') | null;
  description?: string | null;
  /**
   * Select a Lucide icon for this category
   */
  icon?: string | null;
  image?: (string | null) | Media;
  /**
   * Order for display (lower numbers appear first)
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage pickup and dropoff locations for transport and activities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  /**
   * Location name (e.g., "Marrakech Menara Airport", "Jemaa el-Fnaa")
   */
  name: string;
  slug: string;
  /**
   * What this location can be used for
   */
  type: ('pickup' | 'dropoff' | 'activity')[];
  city: 'marrakech' | 'casablanca' | 'agadir' | 'fes' | 'ouarzazate' | 'essaouira' | 'rabat' | 'tangier';
  /**
   * Full address for navigation
   */
  address?: string | null;
  /**
   * GPS coordinates (automatically updated by map picker above)
   */
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * Additional fee for pickup/dropoff from this location (in EUR)
   */
  additionalFee?: number | null;
  /**
   * Special instructions (e.g., "Meet at arrivals terminal")
   */
  notes?: string | null;
  /**
   * Whether this location is currently available for booking
   */
  isActive?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage activities and experiences
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  /**
   * Overall rating from 0 to 5 (e.g., 4.9)
   */
  overallRating?: number | null;
  /**
   * Total number of reviews (e.g., 300)
   */
  totalReviews?: number | null;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Brief description for cards (max 200 chars)
   */
  shortDescription?: string | null;
  /**
   * Optional - can be set after import
   */
  category?: (string | null) | Category;
  /**
   * Duration text (e.g., "Full Day", "2 Hours", "Half Day")
   */
  duration: string;
  /**
   * Activity location (e.g., "Marrakech", "Agafay Desert")
   */
  location?: string | null;
  /**
   * Languages available for this activity/tour
   */
  languages?:
    | {
        language:
          | 'English'
          | 'Francais'
          | 'Espanol'
          | 'German'
          | 'Arabic'
          | 'Italian'
          | 'Portuguese'
          | 'Dutch'
          | 'Russian'
          | 'Chinese'
          | 'Japanese';
        id?: string | null;
      }[]
    | null;
  /**
   * How this activity is priced
   */
  pricingType: 'tiered' | 'custom_note' | 'fixed';
  /**
   * Define pricing tiers - you can set the same number for min and max to show single person pricing
   */
  tieredPricing?: {
    /**
     * Add pricing tiers (e.g., "1 person - €100" or "2-4 people - €50")
     */
    tiers?:
      | {
          /**
           * Number of people (use same for single, or start of range)
           */
          numberOfPeople: number;
          /**
           * Max people (leave empty for single person tier)
           */
          maxPeople?: number | null;
          /**
           * Price per person (EUR)
           */
          pricePerPerson: number;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional: Price for children (EUR). Leave empty if same as adult price.
     */
    childPrice?: number | null;
  };
  /**
   * Display a custom message instead of prices
   */
  customPricingNote?: {
    /**
     * Message to display (e.g., "We will discuss the price when we call you")
     */
    note: string;
  };
  /**
   * Fixed pricing for private tours
   */
  privatePricing?: {
    /**
     * Base price for private tour (EUR)
     */
    basePrice: number;
    /**
     * Minimum guests required
     */
    minGuests?: number | null;
    /**
     * Maximum guests allowed
     */
    maxGuests?: number | null;
    /**
     * Extra charge per guest above minimum (EUR)
     */
    additionalGuestPrice?: number | null;
  };
  /**
   * Required before publishing - can be added after import
   */
  featuredImage?: (string | null) | Media;
  gallery?:
    | {
        media: string | Media;
        type?: ('image' | 'video') | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Key highlights of the experience
   */
  highlights?:
    | {
        highlight: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * What's included in the tour
   */
  included?:
    | {
        item: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * What's NOT included
   */
  notIncluded?:
    | {
        item: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * What to bring / recommendations
   */
  recommendations?:
    | {
        item: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Step-by-step itinerary
   */
  itinerary?:
    | {
        /**
         * e.g., "09:00", "Morning"
         */
        time?: string | null;
        activity: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: Override the auto-generated "About this activity" section. Leave empty to auto-generate from activity fields.
   */
  aboutSection?: {
    features?:
      | {
          icon: 'clock' | 'users' | 'map-pin' | 'globe' | 'star' | 'calendar' | 'camera' | 'sun';
          title: string;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Show this activity on the website
   */
  isActive?: boolean | null;
  /**
   * Feature on homepage
   */
  isFeatured?: boolean | null;
  displayOrder?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
  };
  /**
   * Set start and end locations to display a route map on the activity page
   */
  route?: {
    /**
     * Enable route display on activity page
     */
    enabled?: boolean | null;
    /**
     * Color of the route line on the map
     */
    routeColor?: ('blue' | 'green' | 'red' | 'orange' | 'purple') | null;
    /**
     * Add stops along your route. Minimum 2 required (start and end).
     */
    waypoints?:
      | {
          name: string;
          coordinates?: {
            latitude?: number | null;
            longitude?: number | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Calculated route data (auto-populated when you calculate the route)
     */
    selectedRoute?: {
      /**
       * Encoded polyline geometry
       */
      geometry?: string | null;
      /**
       * Total route distance in meters
       */
      distance?: number | null;
      /**
       * Estimated total duration in seconds
       */
      duration?: number | null;
    };
  };
  /**
   * Quick view of adult price
   */
  groupPrice?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage customer bookings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  /**
   * Auto-generated booking reference
   */
  bookingReference: string;
  status: 'pending' | 'paid' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'refunded' | 'no_show';
  bookingType?: ('activities' | 'transport' | 'combined') | null;
  /**
   * Primary date of the activity/transport
   */
  bookingDate: string;
  /**
   * Preferred time (if applicable)
   */
  bookingTime?: string | null;
  tourType?: ('group' | 'private') | null;
  guestName: string;
  guestEmail: string;
  guestPhone: string;
  guestCountry?: string | null;
  guests: {
    adults: number;
    children?: number | null;
    /**
     * Ages of children (if applicable)
     */
    childrenAges?: string | null;
  };
  /**
   * Dietary restrictions, accessibility needs, special occasions, etc.
   */
  specialRequests?: string | null;
  /**
   * Booked activities/experiences
   */
  activities?:
    | {
        activity?: (string | null) | Activity;
        /**
         * Title at time of booking (for records)
         */
        activityTitle?: string | null;
        date?: string | null;
        /**
         * Number of adults
         */
        adults?: number | null;
        /**
         * Number of children
         */
        children?: number | null;
        /**
         * Legacy field - use adults/children instead
         */
        quantity?: number | null;
        /**
         * If a specific duration/option was selected
         */
        selectedVariant?: {
          variantLabel?: string | null;
          variantPrice?: number | null;
        };
        pricePerAdult: number;
        pricePerChild?: number | null;
        subtotal: number;
        id?: string | null;
      }[]
    | null;
  pickupLocation?: (string | null) | Location;
  /**
   * Custom address if not in location list
   */
  customPickupAddress?: string | null;
  /**
   * Confirmed pickup time
   */
  pickupTime?: string | null;
  dropoffLocation?: (string | null) | Location;
  customDropoffAddress?: string | null;
  /**
   * For airport transfers
   */
  flightDetails?: {
    flightNumber?: string | null;
    airline?: string | null;
    arrivalTime?: string | null;
    departureTime?: string | null;
  };
  pricing: {
    /**
     * Subtotal before discounts (EUR)
     */
    subtotal: number;
    /**
     * Final total (EUR)
     */
    totalAmount: number;
    discountCode?: string | null;
    discountAmount?: number | null;
    /**
     * Additional pickup/dropoff fee
     */
    pickupFee?: number | null;
    currency?: ('EUR' | 'USD' | 'MAD' | 'GBP') | null;
  };
  payment: {
    status: 'pending' | 'processing' | 'paid' | 'failed' | 'refunded' | 'partial_refund';
    method?: ('stripe' | 'paypal' | 'cash' | 'bank_transfer') | null;
    /**
     * Payment gateway transaction ID
     */
    transactionId?: string | null;
    stripeSessionId?: string | null;
    stripePaymentIntentId?: string | null;
    paypalOrderId?: string | null;
    paidAt?: string | null;
    refundAmount?: number | null;
    refundReason?: string | null;
    refundedAt?: string | null;
  };
  /**
   * Internal notes (not visible to customer)
   */
  internalNotes?: string | null;
  /**
   * Assigned driver/guide name
   */
  assignedDriver?: string | null;
  /**
   * Assigned vehicle details
   */
  assignedVehicle?: string | null;
  communicationLog?:
    | {
        date: string;
        type?: ('email' | 'whatsapp' | 'phone' | 'sms') | null;
        message: string;
        sentBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Total booking amount
   */
  totalAmount?: number | null;
  source?: ('website' | 'whatsapp' | 'phone' | 'email' | 'walkin' | 'partner') | null;
  /**
   * Customer preferred language
   */
  language?: ('en' | 'fr' | 'de') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage blog posts and articles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title). Localized for SEO.
   */
  slug: string;
  /**
   * Brief summary for cards and SEO
   */
  excerpt: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: string | Media;
  /**
   * Primary category for this post
   */
  category: 'travel-tips' | 'destinations' | 'culture-history' | 'food-cuisine' | 'adventure' | 'guides' | 'news';
  /**
   * Add tags for better discoverability
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Author name displayed on the post
   */
  author: string;
  /**
   * Estimated reading time in minutes (auto-calculated if empty)
   */
  readingTime?: number | null;
  /**
   * Related activities to show at the end of the post
   */
  relatedActivities?: (string | Activity)[] | null;
  /**
   * Related blog posts to suggest
   */
  relatedPosts?: (string | BlogPost)[] | null;
  seo?: {
    /**
     * Override the page title for SEO (defaults to post title)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines (max 160 chars)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Custom Open Graph image (defaults to featured image)
     */
    ogImage?: (string | null) | Media;
    /**
     * Canonical URL if this is syndicated content
     */
    canonicalUrl?: string | null;
  };
  /**
   * Publication status
   */
  status: 'draft' | 'published' | 'scheduled' | 'archived';
  /**
   * Publication date (for scheduling or display)
   */
  publishedAt?: string | null;
  /**
   * Feature this post on the blog homepage
   */
  isFeatured?: boolean | null;
  /**
   * Order for featured posts (lower = first)
   */
  displayOrder?: number | null;
  /**
   * Allow comments on this post
   */
  allowComments?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status?: ('new' | 'in-progress' | 'replied' | 'closed') | null;
  /**
   * Internal notes about this submission
   */
  notes?: string | null;
  source?: string | null;
  /**
   * Browser info
   */
  userAgent?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  externalUrl?: T;
  _key?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  durationType?: T;
  description?: T;
  icon?: T;
  image?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  city?: T;
  address?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  additionalFee?: T;
  notes?: T;
  isActive?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  overallRating?: T;
  totalReviews?: T;
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  duration?: T;
  location?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  pricingType?: T;
  tieredPricing?:
    | T
    | {
        tiers?:
          | T
          | {
              numberOfPeople?: T;
              maxPeople?: T;
              pricePerPerson?: T;
              id?: T;
            };
        childPrice?: T;
      };
  customPricingNote?:
    | T
    | {
        note?: T;
      };
  privatePricing?:
    | T
    | {
        basePrice?: T;
        minGuests?: T;
        maxGuests?: T;
        additionalGuestPrice?: T;
      };
  featuredImage?: T;
  gallery?:
    | T
    | {
        media?: T;
        type?: T;
        caption?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        highlight?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  recommendations?:
    | T
    | {
        item?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        time?: T;
        activity?: T;
        description?: T;
        id?: T;
      };
  aboutSection?:
    | T
    | {
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  isActive?: T;
  isFeatured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  route?:
    | T
    | {
        enabled?: T;
        routeColor?: T;
        waypoints?:
          | T
          | {
              name?: T;
              coordinates?:
                | T
                | {
                    latitude?: T;
                    longitude?: T;
                  };
              id?: T;
            };
        selectedRoute?:
          | T
          | {
              geometry?: T;
              distance?: T;
              duration?: T;
            };
      };
  groupPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingReference?: T;
  status?: T;
  bookingType?: T;
  bookingDate?: T;
  bookingTime?: T;
  tourType?: T;
  guestName?: T;
  guestEmail?: T;
  guestPhone?: T;
  guestCountry?: T;
  guests?:
    | T
    | {
        adults?: T;
        children?: T;
        childrenAges?: T;
      };
  specialRequests?: T;
  activities?:
    | T
    | {
        activity?: T;
        activityTitle?: T;
        date?: T;
        adults?: T;
        children?: T;
        quantity?: T;
        selectedVariant?:
          | T
          | {
              variantLabel?: T;
              variantPrice?: T;
            };
        pricePerAdult?: T;
        pricePerChild?: T;
        subtotal?: T;
        id?: T;
      };
  pickupLocation?: T;
  customPickupAddress?: T;
  pickupTime?: T;
  dropoffLocation?: T;
  customDropoffAddress?: T;
  flightDetails?:
    | T
    | {
        flightNumber?: T;
        airline?: T;
        arrivalTime?: T;
        departureTime?: T;
      };
  pricing?:
    | T
    | {
        subtotal?: T;
        totalAmount?: T;
        discountCode?: T;
        discountAmount?: T;
        pickupFee?: T;
        currency?: T;
      };
  payment?:
    | T
    | {
        status?: T;
        method?: T;
        transactionId?: T;
        stripeSessionId?: T;
        stripePaymentIntentId?: T;
        paypalOrderId?: T;
        paidAt?: T;
        refundAmount?: T;
        refundReason?: T;
        refundedAt?: T;
      };
  internalNotes?: T;
  assignedDriver?: T;
  assignedVehicle?: T;
  communicationLog?:
    | T
    | {
        date?: T;
        type?: T;
        message?: T;
        sentBy?: T;
        id?: T;
      };
  totalAmount?: T;
  source?: T;
  language?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  readingTime?: T;
  relatedActivities?: T;
  relatedPosts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonicalUrl?: T;
      };
  status?: T;
  publishedAt?: T;
  isFeatured?: T;
  displayOrder?: T;
  allowComments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  source?: T;
  userAgent?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site settings including contact info and social links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  contact: {
    phone: {
      /**
       * Country code with + (e.g., +212 for Morocco)
       */
      countryCode: string;
      /**
       * Phone number without country code (e.g., 777926596)
       */
      number: string;
      /**
       * Formatted display version (e.g., +212 777-926596)
       */
      display?: string | null;
    };
    /**
     * Main contact email address
     */
    email: string;
    address?: {
      /**
       * City or main address line
       */
      line1?: string | null;
      /**
       * Country or secondary address line
       */
      line2?: string | null;
      /**
       * Full address for display
       */
      full?: string | null;
    };
    /**
     * Availability hours (e.g., 24/7, 9AM-6PM)
     */
    availability?: string | null;
  };
  social?: {
    /**
     * Full Facebook page URL
     */
    facebook?: string | null;
    /**
     * Full Instagram profile URL
     */
    instagram?: string | null;
    /**
     * Full YouTube channel URL (optional)
     */
    youtube?: string | null;
    /**
     * Full TikTok profile URL (optional)
     */
    tiktok?: string | null;
    /**
     * Full Twitter/X profile URL (optional)
     */
    twitter?: string | null;
  };
  company: {
    /**
     * Official company name
     */
    name: string;
    /**
     * Short company name for headers/emails
     */
    shortName?: string | null;
    /**
     * Company tagline/slogan
     */
    tagline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the homepage content - Hero, Featured Experiences, Best Trips, About section, FAQ, and SEO settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    /**
     * Hero background (1920x1080px minimum). Used as the first slide in the carousel.
     */
    backgroundImage: string | Media;
    /**
     * Add up to 4 more images. Combined with the Background Image above, they auto-rotate every 5 seconds (5 total max).
     */
    backgroundImages?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Small badge text above headline
     */
    badgeText?: string | null;
    title: string;
    /**
     * Shown in green
     */
    titleHighlight: string;
    description: string;
    /**
     * Green button
     */
    ctaButtonText?: string | null;
    /**
     * Outline button
     */
    secondaryCtaText?: string | null;
    viewAllExperiencesText?: string | null;
    /**
     * Select exactly 2 activities to showcase in the hero
     */
    featuredActivities?: (string | Activity)[] | null;
    credibility?: {
      /**
       * e.g., "500+", "5K+"
       */
      travelersCount?: string | null;
      travelersLabel?: string | null;
      ratingLabel?: string | null;
    };
    scrollText?: string | null;
  };
  categoriesSection?: {
    /**
     * Text shown in the badge above the title
     */
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    seeMoreText?: string | null;
  };
  bestTrips?: {
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    description?: string | null;
    /**
     * Select exactly 4 activities to feature
     */
    activities?: (string | Activity)[] | null;
  };
  about?: {
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    subtitle?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    /**
     * Highlighted closing text
     */
    paragraph3?: string | null;
    /**
     * Small badges highlighting key features
     */
    features?:
      | {
          icon: 'shield' | 'clock' | 'heart' | 'gem' | 'award' | 'star' | 'users' | 'map';
          title: string;
          id?: string | null;
        }[]
      | null;
    ctaButtonText?: string | null;
    secondaryCtaText?: string | null;
    /**
     * Images displayed in a mosaic/bento layout
     */
    images?:
      | {
          image: string | Media;
          /**
           * Describe the image for accessibility
           */
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  packsSection?: {
    /**
     * Text shown in the badge above the title
     */
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    seeMoreText?: string | null;
  };
  blogSection?: {
    /**
     * Text shown in the badge above the title
     */
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    description?: string | null;
    viewAllText?: string | null;
    readMoreText?: string | null;
  };
  reviewsSection?: {
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in TripAdvisor green
     */
    titleHighlight?: string | null;
    happyTravelersLabel?: string | null;
    averageRatingLabel?: string | null;
    wouldRecommendLabel?: string | null;
    tripAdvisorReviewsLabel?: string | null;
    seeAllReviewsText?: string | null;
    seeAllOnTripAdvisorText?: string | null;
    /**
     * Link to your TripAdvisor page
     */
    tripAdvisorUrl?: string | null;
    readMoreText?: string | null;
    seeLessText?: string | null;
    verifiedReviewText?: string | null;
    postedOnTripAdvisorText?: string | null;
  };
  faq?: {
    badgeText?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    description?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    contactCtaText?: string | null;
    contactLinkText?: string | null;
    contactEmail?: string | null;
  };
  seo?: {
    /**
     * Page title in search results (50-60 characters ideal). Leave empty for default.
     */
    metaTitle?: string | null;
    /**
     * Page description in search results (150-160 characters ideal). Leave empty for default.
     */
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  hero?: {
    badge?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    description?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  stats?:
    | {
        value: string;
        label: string;
        icon?: ('clock' | 'users' | 'star' | 'mapPin' | 'award' | 'heart') | null;
        id?: string | null;
      }[]
    | null;
  story?: {
    /**
     * Badge text shown above the title
     */
    badge?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Bullet points shown in the story section
     */
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (string | null) | Media;
    badgeValue?: string | null;
    badgeLabel?: string | null;
  };
  mission?: {
    badge?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Final emphasized paragraph
     */
    goalText?: string | null;
  };
  valuesSection?: {
    badge?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    subtitle?: string | null;
    values?:
      | {
          icon?: ('heart' | 'shield' | 'award' | 'users' | 'star' | 'globe' | 'compass') | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs?: {
    badge?: string | null;
    title?: string | null;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    description?: string | null;
    /**
     * Feature points with checkmarks
     */
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (string | null) | Media;
  };
  teamSection?: {
    title?: string | null;
    subtitle?: string | null;
    members?:
      | {
          name: string;
          role: string;
          bio?: string | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    subtitle?: string | null;
    primaryButtonText?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  header: {
    /**
     * Small badge text above the title
     */
    badgeText?: string | null;
    title: string;
    /**
     * Shown in green
     */
    titleHighlight?: string | null;
    description?: string | null;
  };
  /**
   * Feature highlight cards shown below the hero
   */
  features?:
    | {
        icon: 'heart' | 'calendarX' | 'car' | 'shield' | 'clock' | 'star';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  contactInfo?: {
    address?: {
      line1?: string | null;
      line2?: string | null;
    };
    phone?: {
      number?: string | null;
      /**
       * How the phone number appears (optional)
       */
      display?: string | null;
    };
    email?: {
      address?: string | null;
      responseTime?: string | null;
    };
    whatsapp?: {
      /**
       * Include country code
       */
      number?: string | null;
      /**
       * How the number appears (optional)
       */
      display?: string | null;
      /**
       * Message shown next to WhatsApp number
       */
      message?: string | null;
    };
    workingHours?: {
      title?: string | null;
      line1?: string | null;
      line2?: string | null;
    };
    socialLinks?: {
      instagram?: string | null;
      facebook?: string | null;
      tiktok?: string | null;
      youtube?: string | null;
    };
  };
  formSettings?: {
    title?: string | null;
    submitButtonText?: string | null;
    successMessage?: string | null;
    firstNameLabel?: string | null;
    lastNameLabel?: string | null;
    emailLabel?: string | null;
    phoneLabel?: string | null;
    subjectLabel?: string | null;
    subjectPlaceholder?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    /**
     * Subject options for the dropdown
     */
    subjects?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  labels?: {
    contactInfoTitle?: string | null;
    visitUsTitle?: string | null;
    callUsTitle?: string | null;
    emailUsTitle?: string | null;
    whatsappTitle?: string | null;
    followUsTitle?: string | null;
  };
  faq?: {
    title?: string | null;
    questions?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  map?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Google Maps embed URL
     */
    embedUrl?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page".
 */
export interface TermsPage {
  id: string;
  title: string;
  /**
   * When the terms were last updated
   */
  lastUpdated?: string | null;
  /**
   * The full terms and conditions content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: string;
  title: string;
  /**
   * When the privacy policy was last updated
   */
  lastUpdated?: string | null;
  /**
   * The full privacy policy content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phone?:
          | T
          | {
              countryCode?: T;
              number?: T;
              display?: T;
            };
        email?: T;
        address?:
          | T
          | {
              line1?: T;
              line2?: T;
              full?: T;
            };
        availability?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        twitter?: T;
      };
  company?:
    | T
    | {
        name?: T;
        shortName?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        backgroundImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        ctaButtonText?: T;
        secondaryCtaText?: T;
        viewAllExperiencesText?: T;
        featuredActivities?: T;
        credibility?:
          | T
          | {
              travelersCount?: T;
              travelersLabel?: T;
              ratingLabel?: T;
            };
        scrollText?: T;
      };
  categoriesSection?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        seeMoreText?: T;
      };
  bestTrips?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        activities?: T;
      };
  about?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        subtitle?: T;
        paragraph1?: T;
        paragraph2?: T;
        paragraph3?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              id?: T;
            };
        ctaButtonText?: T;
        secondaryCtaText?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  packsSection?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        seeMoreText?: T;
      };
  blogSection?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        viewAllText?: T;
        readMoreText?: T;
      };
  reviewsSection?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        happyTravelersLabel?: T;
        averageRatingLabel?: T;
        wouldRecommendLabel?: T;
        tripAdvisorReviewsLabel?: T;
        seeAllReviewsText?: T;
        seeAllOnTripAdvisorText?: T;
        tripAdvisorUrl?: T;
        readMoreText?: T;
        seeLessText?: T;
        verifiedReviewText?: T;
        postedOnTripAdvisorText?: T;
      };
  faq?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        contactCtaText?: T;
        contactLinkText?: T;
        contactEmail?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        backgroundImage?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  story?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        badgeValue?: T;
        badgeLabel?: T;
      };
  mission?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        goalText?: T;
      };
  valuesSection?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        subtitle?: T;
        values?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  teamSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              image?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        badgeText?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        address?:
          | T
          | {
              line1?: T;
              line2?: T;
            };
        phone?:
          | T
          | {
              number?: T;
              display?: T;
            };
        email?:
          | T
          | {
              address?: T;
              responseTime?: T;
            };
        whatsapp?:
          | T
          | {
              number?: T;
              display?: T;
              message?: T;
            };
        workingHours?:
          | T
          | {
              title?: T;
              line1?: T;
              line2?: T;
            };
        socialLinks?:
          | T
          | {
              instagram?: T;
              facebook?: T;
              tiktok?: T;
              youtube?: T;
            };
      };
  formSettings?:
    | T
    | {
        title?: T;
        submitButtonText?: T;
        successMessage?: T;
        firstNameLabel?: T;
        lastNameLabel?: T;
        emailLabel?: T;
        phoneLabel?: T;
        subjectLabel?: T;
        subjectPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        subjects?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  labels?:
    | T
    | {
        contactInfoTitle?: T;
        visitUsTitle?: T;
        callUsTitle?: T;
        emailUsTitle?: T;
        whatsappTitle?: T;
        followUsTitle?: T;
      };
  faq?:
    | T
    | {
        title?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  map?:
    | T
    | {
        title?: T;
        subtitle?: T;
        embedUrl?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page_select".
 */
export interface TermsPageSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}